baseURL = "https://migel0.github.io"
languageCode = "en-us"
defaultContentLanguage   = "en"
isMultilingual           = false
title                    = "$cat Notes.txt"
theme                    = "sam"
pygmentsStyle            = "monokai"                        # https://help.farbox.com/pygments.html
pygmentsCodefences       = true
# googleAnalytics        = ""
#publishDir = "docs"
[params]
    dateform             = "Mon Jan 02, 2006"
    dateformfull         = "Mon Jan 2 2006 15:04:05 EST"
    favicon              = "sam.ico"
    homepage             = "main"                           # What to call the home page link
    footerText           = ""
# Metadata for Open Graph and Twitter
    description          = "A new Hugo site."               # Max 160 characters show in search results
#   images               = ["tn.png"]                       # Image that shows on Twitter cards and Open Graph links to the site
    title                = "$cat Notes.txt"
    # rss                = ""

[[params.mainMenu]]

    link = "/post"
    text = "Notes.txt"
#


#[[params.mainMenu]]
#    link = "/photography"
#    text = "photography"
#[[params.mainMenu]]
#    link = "/about"
#    text = "who dis?"

#[[params.videoBackground.sources]]
#    source  = "/sample_video.mp4"
#    type    = "video/mp4"
#    poster  = "/background.png"
#[params.videoBackground]
#    overlay = "rgba(0, 0, 0, 0.4)" # optional
#
#[[params.mainMenu]]
#    link = "posts"
#    text = "posts"
#
#[[params.mainMenu]]
#    link = "gallery"
#    text = "gallery"
#
#[[params.mainMenu]]
#    link = "portfolio"
#    text = "portfolio"
#
#[[params.mainMenu]]
#    link = "about"
#    text = "who is sam?"
#
#[imaging]
#    quality = 75
#